### ISSUE TITLE
Changement d'administration dans l'AÉDIROUM

### ISSUE THREAD

**Issue by leo-ard** [AEDIROUM/aediroum.ca#41]
Bonjour ! Je suis le nouveau président de l'asso et j'aurais besoin d'accès au répo. Est-ce que ce serait possible de me donner les droits @brilhana ou @abdelq ?

Merci beaucoup !

Léonard Oest O'Leary
Nouvellement président de l'asso

**Comment by abdelq** [comment]
Je ne suis plus membre de ce groupe. Peut-être que @alizeegagnon a les droits?

**Comment by alizeegagnon** [comment]
Oui, on dirait que j'ai les droits. Je dois aller où pour changer les membres du groupe ? 

Félicitations pour ton nouveau poste @lool01 :)

**Comment by leo-ard** [comment]
Merci beaucoup @alizeegagnon et @abdelq :) Je pense que tu peux get de l'info sur comment ajouter quelqu'un [ici](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-organization-members-to-a-team)

**Comment by leo-ard** [comment]
Aussi, je me demandais si le site web était toujours host sur arcade ? Parce que j'ai regardé rapidement et ça semble plus être le cas... En tout cas pas dans ~/public_html comme le laisse sugérer le script de déploiement 

EDIT : finalement j'ai trouvé

**Comment by alizeegagnon** [comment]
Tu as été invité ! Je me retirerai le titre "owner" quand tu auras accepté.

**Comment by leo-ard** [comment]
C'est bon, j'ai rejoins ! Merci beaucoup @alizeegagnon !

**Comment by alizeegagnon** [comment]
En fait on dirait que c'est toi qui doit m'enlever !

**Comment by leo-ard** [comment]
hahaha ok, bye bye dans ce cas 👋
